services:
  manticore:
    image: manticoresearch/manticore
    ports:
      - 127.0.0.1:9308:9308
    volumes:
      - ./var/sphinx/data:/var/lib/manticore/data
      - ./docker/manticore/manticore.conf:/etc/manticoresearch/manticore.conf
  manticore-test:
    image: manticoresearch/manticore
    ports:
      - 127.0.0.1:9309:9308
    volumes:
      - ./var/manticore-test/data:/var/lib/manticore/data
      - ./docker/manticore/manticore.conf:/etc/manticoresearch/manticore.conf
  mongo:
    image: mongo:5.0.9-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./var/mongo/data:/data/db
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 12345678
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
    volumes:
      - ./var/minio/data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: curl -I http://localhost:9000/minio/health/live
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 10s
  minio-setup:
    build: docker/minio-setup
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 12345678
    depends_on:
      minio:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
