version: '3.4'
services:
  sphinx:
    build: docker/sphinx
    environment:
      SOURCE_DB: demo-app
      SOURCE_USER: root
      SOURCE_PASSWORD: 123456
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:9306:9306
    volumes:
      - ./var/sphinx/data:/usr/local/sphinx/var/data/
      - ./var/sphinx/logs:/usr/local/sphinx/var/log/
    command: sleep infinity
  sphinx-test:
    build: docker/sphinx
    environment:
      SOURCE_DB: demo-app-test
      SOURCE_USER: root
      SOURCE_PASSWORD: 123456
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:9307:9306
    volumes:
      - ./var/sphinx-test/data:/usr/local/sphinx/var/data/
      - ./var/sphinx-test/logs:/usr/local/sphinx/var/log/
  mongo:
    image: mongo:5.0.9-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./var/mongo/data:/data/db
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 12345678
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
    volumes:
      - ./var/minio/data:/data
    command: server /data --console-address ":9001"
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
