apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-consumer-deployment
  labels:
    app: node-api-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-api-demo-app
      component: image-consumer
  template:
    metadata:
      labels:
        app: node-api-demo-app
        component: image-consumer
    spec:
      containers:
        - name: image-consumer
          image: node-api-demo-app-image-consumer:0.1.9
          imagePullPolicy: Never
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
